{
 "title": "Dashboard Copy",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  { "title": "APP METRICS (RED METHOD)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Latency (P95 & P99)",
   "type": "timeseries",
   "description": "Mục đích: Chứng minh khi RPS tăng mạnh, hệ thống bắt đầu phản hồi chậm.",
   "gridPos": { "h": 9, "w": 16, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_request_duration_seconds_bucket[1m])) by (le))",
     "legendFormat": "P95 Latency"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(http_request_duration_seconds_bucket[1m])) by (le))",
     "legendFormat": "P99 Latency"
    }
   ]
  },
  {
   "title": "Error Rate",
   "type": "stat",
   "description": "Mục đích: Hiển thị ngay lập tức nếu hệ thống sập và trả về lỗi 50x.",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(http_requests_total{status=~\"5..\"}[1m])) / sum(rate(http_requests_total[1m])) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Success Checkout",
   "type": "timeseries",
   "description": "Mục đích: Đo lường hiệu quả kinh doanh thực tế.",
   "gridPos": { "h": 9, "w": 10, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(increase(business_success_checkout_total[1m]))",
     "legendFormat": "Successful orders per minute"
    }
   ]
  },
  {
   "title": "Throughput (RPS)",
   "type": "timeseries",
   "description": "Đo lường lưu lượng yêu cầu (Requests Per Second) theo thời gian thực. Giúp đánh giá tải trọng người dùng đang tác động lên hệ thống",
   "gridPos": { "h": 9, "w": 14, "x": 10, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(http_requests_total[1m])) by (method)",
     "legendFormat": "{{method}}"
    }
   ]
  },
  { "title": "INFRA METRICS (USE METHOD)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "CPU Usage vs Quota",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{container_label_com_docker_compose_service=\"backend\"}[1m])) * 100",
     "legendFormat": "CPU usage rate (%)"
    }
   ]
  },
  {
   "title": "CPU Throttling",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_cfs_throttled_periods_total{container_label_com_docker_compose_service=\"backend\"}[1m]))",
     "legendFormat": "CPU throttling rate"
    }
   ]
  },
  {
   "title": "Network I/O",
   "type": "timeseries",
   "description": "Mục đích: Theo dõi lượng dữ liệu truyền ra/vào.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "Bytes/sec (IEC)" } },
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_bytes_total{container_label_com_docker_compose_service=\"backend\"}[1m]))",
     "legendFormat": "Inbound (bytes/sec)"
    },
    {
     "expr": "-sum(rate(container_network_transmit_bytes_total{container_label_com_docker_compose_service=\"backend\"}[1m]))",
     "legendFormat": "Outbound (bytes/sec)"
    }
   ]
  },
  {
   "title": "Memory Working Set",
   "type": "timeseries",
   "description": "Mục đích: Chứng minh app không bị tràn RAM (Memory Leak).",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "Bytes (IEC)" } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{container_label_com_docker_compose_service=\"backend\"})",
     "legendFormat": "memory usage"
    }
   ]
  },
  {
   "title": "DATABASE & CACHE METRICS (THE ROOT CAUSE)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 }
  },
  {
   "title": "Redis Cache Hit Ratio",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(redis_cache_hits_total[1m])) / (sum(rate(redis_cache_hits_total[1m])) + sum(rate(redis_cache_misses_total[1m]))) * 100",
     "legendFormat": "Hit Rate"
    }
   ]
  },
  {
   "title": "Lock Failures / Write Conflicts ",
   "type": "timeseries",
   "description": "Mục đích: Bằng chứng cho kịch bản Flash Sale - Khách hàng đang đạp lên nhau để mua hàng.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(increase(lock_failures_total[1m]))",
     "legendFormat": "Write Conflicts"
    }
   ]
  },
  {
   "title": "Database Slow Queries",
   "type": "timeseries",
   "description": "Mục đích: Đo lường tốc độ móc dữ liệu thực tế của Mongoose",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(db_query_duration_seconds_bucket[1m])) by (le))",
     "legendFormat": "DB Latency (P95)"
    }
   ]
  },
  {
   "title": "MongoDB Active Connections",
   "type": "stat",
   "description": "Mục đích: Xem lượng kết nối có bị chạm trần (Max Pool Size) không",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 45 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mongodb_connections_current{state=\"current\"}",
     "legendFormat": "Total Connections"
    }
   ]
  },
  { "title": "SCALABILITY & ORCHESTRATION", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 53 } },
  {
   "title": "Backend Instance Count",
   "type": "state-timeline",
   "description": "Mục đích: Chứng minh khả năng tự co giãn (Scale out).",
   "gridPos": { "h": 11, "w": 17, "x": 4, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "count(container_last_seen{container_label_com_docker_compose_service=\"backend\"})",
     "legendFormat": "Instance Count"
    }
   ]
  }
 ]
}